/**
 * Analytics PDF Generation
 * Creates PDF reports for form analytics using @react-pdf/renderer
 *
 * Install: npm install @react-pdf/renderer
 */

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  Font,
} from '@react-pdf/renderer';

// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #3b82f6',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e40af',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
  },
  section: {
    marginTop: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e3a8a',
    marginBottom: 10,
    borderBottom: '1 solid #cbd5e1',
    paddingBottom: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
  },
  statCard: {
    width: '47%',
    backgroundColor: '#f8fafc',
    padding: 12,
    borderRadius: 4,
    border: '1 solid #e2e8f0',
  },
  statLabel: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0f172a',
  },
  table: {
    marginTop: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #e2e8f0',
    paddingVertical: 8,
  },
  tableHeader: {
    backgroundColor: '#f1f5f9',
    fontWeight: 'bold',
  },
  tableCell: {
    fontSize: 10,
    padding: 4,
  },
  chartContainer: {
    marginTop: 15,
    marginBottom: 15,
    alignItems: 'center',
  },
  chartImage: {
    maxWidth: '100%',
    maxHeight: 300,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#94a3b8',
    borderTop: '1 solid #e2e8f0',
    paddingTop: 10,
  },
  brandingSection: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    width: 40,
    height: 40,
  },
  metadata: {
    fontSize: 9,
    color: '#94a3b8',
    marginTop: 5,
  },
});

interface AnalyticsPDFProps {
  formTitle: string;
  formDescription?: string;
  stats: {
    totalResponses: number;
    completedResponses: number;
    incompleteResponses: number;
    completionRate: number;
    avgCompletionTime: number;
  };
  questionStats?: Array<{
    title: string;
    type: string;
    responseCount: number;
    skipCount?: number;
    // Advanced statistics for numeric questions
    mean?: number;
    median?: number;
    stdDev?: number;
    confidenceInterval?: { lowerBound: number; upperBound: number };
    quartiles?: { q1: number; q2: number; q3: number; iqr: number };
    outliers?: { count: number; percentage: number };
    normality?: { skewness: number; kurtosis: number; isNormal: boolean };
  }>;
  chartImages?: {
    responsesTrend?: string; // Base64 encoded image
    completionRate?: string;
    topAnswers?: string;
  };
  branding?: {
    logo?: string; // Base64 encoded logo
    companyName?: string;
    primaryColor?: string;
  };
  // New: Response velocity metrics
  velocity?: {
    responsesPerDay: number;
    responsesPerHour: number;
    trend: 'increasing' | 'decreasing' | 'stable';
    peakHour: number | null;
  };
  // New: Date range filter
  dateRange?: {
    startDate: Date | null;
    endDate: Date | null;
    preset: string;
  };
  generatedAt: Date;
  generatedBy: string;
}

export function AnalyticsPDF({
  formTitle,
  formDescription,
  stats,
  questionStats = [],
  chartImages = {},
  branding,
  velocity,
  dateRange,
  generatedAt,
  generatedBy,
}: AnalyticsPDFProps) {
  const formatTime = (seconds: number): string => {
    if (seconds < 60) return `${Math.round(seconds)}s`;
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.round(seconds % 60);
    return `${minutes}m ${remainingSeconds}s`;
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.brandingSection}>
            <View>
              <Text style={styles.title}>{formTitle}</Text>
              {formDescription && (
                <Text style={styles.subtitle}>{formDescription}</Text>
              )}
            </View>
            {branding?.logo && (
              <Image src={branding.logo} style={styles.logo} />
            )}
          </View>
          <Text style={styles.metadata}>
            Generated on {generatedAt.toLocaleDateString()} at {generatedAt.toLocaleTimeString()}
          </Text>
          <Text style={styles.metadata}>
            Generated by {generatedBy}
          </Text>
          {dateRange && (dateRange.startDate || dateRange.endDate) && (
            <Text style={styles.metadata}>
              Date Range: {dateRange.preset === 'all' ? 'All Time' :
                dateRange.startDate && dateRange.endDate
                  ? `${dateRange.startDate.toLocaleDateString()} - ${dateRange.endDate.toLocaleDateString()}`
                  : dateRange.startDate
                  ? `From ${dateRange.startDate.toLocaleDateString()}`
                  : `Until ${dateRange.endDate?.toLocaleDateString()}`}
            </Text>
          )}
        </View>

        {/* Overview Statistics */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Overview</Text>
          <View style={styles.statsGrid}>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Total Responses</Text>
              <Text style={styles.statValue}>{stats.totalResponses}</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Completed</Text>
              <Text style={styles.statValue}>{stats.completedResponses}</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Incomplete</Text>
              <Text style={styles.statValue}>{stats.incompleteResponses}</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Completion Rate</Text>
              <Text style={styles.statValue}>{stats.completionRate.toFixed(1)}%</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Avg. Completion Time</Text>
              <Text style={styles.statValue}>
                {formatTime(stats.avgCompletionTime)}
              </Text>
            </View>
          </View>
        </View>

        {/* Response Velocity */}
        {velocity && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Response Velocity</Text>
            <View style={styles.statsGrid}>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>Responses per Day</Text>
                <Text style={styles.statValue}>{velocity.responsesPerDay.toFixed(1)}</Text>
              </View>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>Responses per Hour</Text>
                <Text style={styles.statValue}>{velocity.responsesPerHour.toFixed(2)}</Text>
              </View>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>Trend</Text>
                <Text style={styles.statValue}>
                  {velocity.trend.charAt(0).toUpperCase() + velocity.trend.slice(1)}
                </Text>
              </View>
              {velocity.peakHour !== null && (
                <View style={styles.statCard}>
                  <Text style={styles.statLabel}>Peak Hour</Text>
                  <Text style={styles.statValue}>{velocity.peakHour}:00</Text>
                </View>
              )}
            </View>
          </View>
        )}

        {/* Response Trend Chart */}
        {chartImages.responsesTrend && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Response Trends</Text>
            <View style={styles.chartContainer}>
              <Image src={chartImages.responsesTrend} style={styles.chartImage} />
            </View>
          </View>
        )}

        {/* Question Statistics Table */}
        {questionStats.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Question Statistics</Text>
            <View style={styles.table}>
              {/* Table Header */}
              <View style={[styles.tableRow, styles.tableHeader]}>
                <Text style={[styles.tableCell, { flex: 3 }]}>Question</Text>
                <Text style={[styles.tableCell, { flex: 1 }]}>Type</Text>
                <Text style={[styles.tableCell, { flex: 1, textAlign: 'right' }]}>
                  Responses
                </Text>
                <Text style={[styles.tableCell, { flex: 1, textAlign: 'right' }]}>
                  Skip Rate
                </Text>
              </View>
              {/* Table Rows */}
              {questionStats.slice(0, 20).map((q, index) => {
                const totalAttempts = q.responseCount + (q.skipCount || 0);
                const skipRate = totalAttempts > 0
                  ? ((q.skipCount || 0) / totalAttempts * 100).toFixed(1)
                  : '0.0';

                return (
                  <View key={index} style={styles.tableRow}>
                    <Text style={[styles.tableCell, { flex: 3 }]}>
                      {q.title.length > 50 ? `${q.title.substring(0, 50)}...` : q.title}
                    </Text>
                    <Text style={[styles.tableCell, { flex: 1 }]}>{q.type}</Text>
                    <Text style={[styles.tableCell, { flex: 1, textAlign: 'right' }]}>
                      {q.responseCount}
                    </Text>
                    <Text style={[styles.tableCell, { flex: 1, textAlign: 'right' }]}>
                      {skipRate}%
                    </Text>
                  </View>
                );
              })}
            </View>
            {questionStats.length > 20 && (
              <Text style={[styles.metadata, { marginTop: 8 }]}>
                Showing first 20 of {questionStats.length} questions
              </Text>
            )}
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>
            {branding?.companyName || 'StatQ'} - Analytics Report
          </Text>
          <Text>
            Generated with StatQ • https://statq.ai
          </Text>
        </View>
      </Page>

      {/* Page 2: Advanced Question Statistics */}
      {questionStats.some(q => q.mean !== undefined || q.quartiles !== undefined) && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Detailed Statistics (Numeric Questions)</Text>

          {questionStats.filter(q => q.mean !== undefined).map((q, index) => (
            <View key={index} style={styles.section}>
              <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 8 }}>
                {q.title}
              </Text>

              <View style={styles.statsGrid}>
                {q.mean !== undefined && (
                  <View style={styles.statCard}>
                    <Text style={styles.statLabel}>Mean</Text>
                    <Text style={styles.statValue}>{q.mean.toFixed(2)}</Text>
                    {q.confidenceInterval && (
                      <Text style={{ fontSize: 8, color: '#64748b', marginTop: 2 }}>
                        95% CI: {q.confidenceInterval.lowerBound.toFixed(2)} - {q.confidenceInterval.upperBound.toFixed(2)}
                      </Text>
                    )}
                  </View>
                )}
                {q.median !== undefined && (
                  <View style={styles.statCard}>
                    <Text style={styles.statLabel}>Median</Text>
                    <Text style={styles.statValue}>{q.median.toFixed(2)}</Text>
                  </View>
                )}
                {q.stdDev !== undefined && (
                  <View style={styles.statCard}>
                    <Text style={styles.statLabel}>Std. Deviation</Text>
                    <Text style={styles.statValue}>{q.stdDev.toFixed(2)}</Text>
                  </View>
                )}
                {q.quartiles && (
                  <>
                    <View style={styles.statCard}>
                      <Text style={styles.statLabel}>Q1 (25th)</Text>
                      <Text style={styles.statValue}>{q.quartiles.q1.toFixed(2)}</Text>
                    </View>
                    <View style={styles.statCard}>
                      <Text style={styles.statLabel}>Q3 (75th)</Text>
                      <Text style={styles.statValue}>{q.quartiles.q3.toFixed(2)}</Text>
                    </View>
                    <View style={styles.statCard}>
                      <Text style={styles.statLabel}>IQR</Text>
                      <Text style={styles.statValue}>{q.quartiles.iqr.toFixed(2)}</Text>
                    </View>
                  </>
                )}
                {q.outliers && (
                  <View style={styles.statCard}>
                    <Text style={styles.statLabel}>Outliers</Text>
                    <Text style={styles.statValue}>{q.outliers.count}</Text>
                    <Text style={{ fontSize: 8, color: '#64748b', marginTop: 2 }}>
                      {q.outliers.percentage.toFixed(1)}% of data
                    </Text>
                  </View>
                )}
                {q.normality && (
                  <View style={styles.statCard}>
                    <Text style={styles.statLabel}>Normality</Text>
                    <Text style={styles.statValue}>
                      {q.normality.isNormal ? '✓ Normal' : '! Non-normal'}
                    </Text>
                    <Text style={{ fontSize: 8, color: '#64748b', marginTop: 2 }}>
                      Skew: {q.normality.skewness.toFixed(2)}
                    </Text>
                  </View>
                )}
              </View>
            </View>
          ))}

          <View style={styles.footer}>
            <Text>
              {branding?.companyName || 'StatQ'} - Advanced Statistics (Page 2)
            </Text>
          </View>
        </Page>
      )}

      {/* Page 3: Charts (if available) */}
      {(chartImages.completionRate || chartImages.topAnswers) && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Visualizations</Text>

          {chartImages.completionRate && (
            <View style={styles.section}>
              <Text style={{ fontSize: 14, marginBottom: 10, fontWeight: 'bold' }}>
                Completion Rate Over Time
              </Text>
              <View style={styles.chartContainer}>
                <Image src={chartImages.completionRate} style={styles.chartImage} />
              </View>
            </View>
          )}

          {chartImages.topAnswers && (
            <View style={styles.section}>
              <Text style={{ fontSize: 14, marginBottom: 10, fontWeight: 'bold' }}>
                Top Answers Distribution
              </Text>
              <View style={styles.chartContainer}>
                <Image src={chartImages.topAnswers} style={styles.chartImage} />
              </View>
            </View>
          )}

          <View style={styles.footer}>
            <Text>
              {branding?.companyName || 'StatQ'} - Visualizations (Page 3)
            </Text>
          </View>
        </Page>
      )}
    </Document>
  );
}
